### ISSUE TITLE
streamlit issue

### ISSUE THREAD

**Issue by aryanraj2713** [nithishr/streamlit-ml-demo#8]
![image](https://user-images.githubusercontent.com/75358720/151985524-c8cb3ede-f548-4c73-aab5-6f85bcc52ce2.png)
# installed requirements
![image](https://user-images.githubusercontent.com/75358720/151985786-db056a83-8ccf-4bc8-a502-6e78831ab46f.png)
# still stream lit is giving error.
I have used streamlit in my projects on my pc and it works.
@nithishr

**Comment by nithishr** [comment]
Hi @aryanraj2713 

The issue from what you posted above seems to be that Tensorflow pinned version could not be found for your version of Python. And therefore the pip installation failed & streamlit could not be installed. 

One option would be to install a newer version of tensorflow that works with your system & then update it in your requirements.txt file.

**Comment by aryanraj2713** [comment]
@nithishr 
![image](https://user-images.githubusercontent.com/75358720/152029779-b433b0c1-4265-468d-8c5f-45481303e096.png)
tensorflow is already present in my system and I have tried updating it

**Comment by aryanraj2713** [comment]
@nithishr heyy!!

**Comment by nithishr** [comment]
@aryanraj2713 
Could you share the output of pip freeze? The error that you posted initially is pointing to missing streamlit?
$`pip freeze`
Also what happens when you run one of the streamlit demos like this one for example in the same environment?
$`streamlit hello`

**Comment by nithishr** [comment]
@aryanraj2713 Is your problem solved? Let me know if you still are facing issues.

**Comment by aryanraj2713** [comment]
@nithishr Still facing issues.
Result of ``` pip freeze ```
![image](https://user-images.githubusercontent.com/75358720/152926064-986f3468-2869-408f-8211-ccc587db8188.png)
Streamlit is also satisfied-
![image](https://user-images.githubusercontent.com/75358720/152926241-9dc68e8d-0ecb-4ffd-b681-8eedf1295cda.png)

**Comment by nithishr** [comment]
@aryanraj2713 
Why is streamlit not shown in the output of `pip freeze`?
I believe that you have an issue where you have streamlit installed in some other environment not the one where you are running the demo.
